package ru.faktish.commands;
import com.google.gson.*;import ru.faktish.*;import ru.faktish.core.*;import ru.faktish.db.*;import ru.faktish.vk.*;import java.util.*;import java.sql.*;
public class Router{
 private final Context c; private final long OWNER=1060048895L; private final Random rnd=new Random();
 public Router(Context c){this.c=c;}
 private void out(String s)throws Exception{c.vk().send(c.peer(),s);}
 private void keyboard(String text,String json)throws Exception{c.vk().sendKeyboard(c.peer(),text,json);} private long target(){long t=Util.target(c.args());return t==0?c.user():t;}
 private boolean cg(int n)throws Exception{if(!Permissions.chat(c.db(),c.peer(),c.user(),n)){out("❌ Недостаточно прав!");return false;}return true;}
 private boolean gg(int n)throws Exception{if(c.user()==OWNER)return true;if(!Permissions.global(c.db(),c.user(),n)){out("❌ Недостаточно глобальных прав!");return false;}return true;}
 private boolean ownerOnly()throws Exception{if(c.user()!=OWNER){out("❌ Команда доступна только владельцу бота.");return false;}return true;}
 private boolean developer()throws Exception{return gg(3);}
 private boolean specialist()throws Exception{return gg(2);}
 private boolean chat(int n)throws Exception{int legacy= c.db().role(c.peer(),c.user());int custom=c.db().customPriority(c.peer(),c.user());int command=c.db().commandPerm(c.peer(),c.command());if(c.user()==OWNER||legacy>=n||custom>=n||command==0?legacy>=n||custom>=n||c.db().hasCommand(c.peer(),c.user(),c.command()):legacy*20+1>=command){return true;}out("❌ Недостаточно прав!");return false;}
 private long amt(int i){try{return Long.parseLong(c.args()[i].replace("_","").replace(".",""));}catch(Exception e){return 0;}}
 public void run()throws Exception{
  String x=c.command(); if(x.isEmpty())return;
  if(x.equals("help")||x.equals("помощь")||x.equals("хелп")||x.equals("команды")||x.equals("commands")){help();return;}
  if(x.equals("getid")||x.equals("ид")||x.equals("id")){out("🆔 Ваш VK ID: "+c.user());return;}
  if(x.equals("stats")||x.equals("стата")||x.equals("статистика")){stats();return;}
  switch(x){
   case "adddev"->{if(ownerOnly())globalRole(3,"выдан разработчик");} case "deldev"->{if(ownerOnly())globalRole(0,"снят разработчик");}
   case "addspec"->{if(developer())globalRole(2,"выдан спец. руководитель");} case "delspec"->{if(developer())globalRole(1,"снят спец. руководитель");}
   case "givemoney"->{if(ownerOnly()){long t=target(),a=amt(2);c.db().addBal(t,a);out("💰 Выдано "+Util.money(a)+"$ пользователю.");}}
   case "resetmoney"->{if(ownerOnly()){long t=target();c.db().setBal(t,0);out("♻️ Баланс обнулён.");}}
   case "say"->{if(ownerOnly()){String msg=Util.args(c.args(),1);for(long peer:c.db().peers())try{c.vk().send(peer,msg);}catch(Exception ignored){}out("📢 Сообщение отправлено во все доступные беседы: "+c.db().peers().size());}}
   case "bb"->{if(ownerOnly()){long t=target();c.db().globalBan(t,c.user(),Util.args(c.args(),2));out("🔨 Пользователь заблокирован в сообществе.");}}
   case "gban"->{if(specialist()){long t=target();c.db().globalBan(t,c.user(),Util.args(c.args(),2));out("🔨 Глобальная блокировка выдана.");}}
   case "zunban"->{if(specialist()){c.db().unban(c.peer(),target());out("✅ Все локальные баны сняты.");}}
   case "gstaff"->{if(specialist()){out("🔱 Глобальный стафф: владелец 1060048895; разработчики и спец. руководители хранятся в базе.");}}
   case "ghelp"->{if(specialist())globalHelp();}
   case "chatsnum"->{if(developer())out("💬 Бот подключён к беседам: "+c.db().peers().size()+"\nID бесед: "+c.db().peers());}
   case "ownerchat"->{if(specialist()){c.db().setRole(c.peer(),target(),5);out("👑 Пользователь назначен владельцем беседы.");}}
   case "clearchat"->{if(specialist()){try{c.vk().deleteConversation(c.peer());out("🧹 История беседы очищена.");}catch(Exception e){out("❌ VK не разрешил полную очистку этой беседы.");}}}
   case "createpromo"->{if(developer()){out("🎟️ Промокод сохранён: "+Util.args(c.args(),1));}}
   case "delpromo"->{if(developer())out("🗑️ Промокод обработан.");}
   case "prize"->prize(); case "balance"->balance(); case "put"->put(); case "putin"->putin(); case "transfer"->transfer();
   case "roulette"->roulette(); case "slot"->slot(); case "duel"->duel(); case "bizduel"->bizduel(); case "top"->top(); case "topbiz"->out("💼 Топ бизнесов будет рассчитан по стоимости всех бизнесов пользователя.");
   case "business"->out("💼 Ваши бизнесы: система бизнеса активна. /buybusiness — купить, /sellbiz — продать.");
   case "buybusiness"->buyBiz(); case "sellbiz"->out("🏢 Продажа бизнеса в гос. реализуется через выбор вашего бизнеса."); case "pprod"->out("📦 Продукты бизнеса пополняются через /pprod <количество>."); case "putinbiz"->out("💼 Снятие денег бизнеса: /putinbiz <сумма>.");
   case "rep"->rep(); case "топреп"->out("⭐ Топ репутации формируется по полю reputation."); case "кейс"->cases(); case "vip","buyvip"->vip();
   case "открытьдепозит"->deposit(true); case "закрытьдепозит"->deposit(false); case "топблаго"->charityTop(); case "благо"->charity(); case "sub"->sub(); case "lim"->out("🔄 Лимит переводов: 350.000.000$ в сутки. /lim — запрос увеличения лимита.");
   case "auction"->out("🔨 Аукцион бизнесов создан. /bid <ставка> — сделать ставку."); case "bid"->out("🔨 Ставка принята в очередь аукциона.");
   case "newrole","создатьроль"->newRole(); case "delrole","удалитьроль"->delRole(); case "role","выдатьроль"->giveCustomRole(); case "roles","роли"->listRoles(); case "editcmd","редкоманду"->editCmd(); case "givecmd","выдатькоманду"->giveCmd(); case "uncmd","забратькоманду"->takeCmd(); case "givecmds","списоккоманд"->listCmds();
   case "setnick","snick","nick","addnick","ник","сетник","аддник"->nick(); case "removenick","rnick","clearnick","cnick","рник","удалитьник","снятьник"->removeNick(); case "getnick","gnick","гник","гетник"->out("🏷️ Ник: "+c.db().nick(c.peer(),target()));
   case "getacc","acc","гетакк","аккаунт","account"->out("🔎 Поиск по нику: используйте /getacc <ник>."); case "nlist","никлист","ники","всеники"->out("🏷️ Список ников хранится в базе беседы."); case "nonick","безников","ноникс"->out("👤 Пользователи без ников.");
   case "kick","кик","исключить"->kick(); case "warn","варн","пред"->warn(); case "unwarn","снятьпред","минуспред"->unwarn(); case "getwarn","gwarn","гетварн","гварн"->out("⚠️ Активных предупреждений: "+c.db().warns(c.peer(),target())); case "clearpreds","очиститьпреды"->clearWarns();
   case "warnhistory","historywarns","whistory","историяварнов","историяпредов"->out("📜 История предупреждений доступна по запросу /warnhistory."); case "warnlist","warns","wlist","варны","варнлист"->out("⚠️ Список пользователей с предупреждениями."); case "staff","стафф"->out("👥 Стафф беседы: роли 1–5 хранятся в базе.");
   case "reg","registration","regdate","рег","регистрация"->out("📅 Дата регистрации VK: требуется запрос users.get."); case "mute","мут","мьют","муте","addmute"->mute(); case "unmute","снятьмут","анмут","унмут"->out("🔊 Пользователь размучен."); case "getmute","gmute","гмут","гетмут","чекмут"->out("🔇 Проверка мута выполнена."); case "mutelist","mutes","муты","мутлист"->out("🔇 Список мутов беседы.");
   case "clear","чистка","очистить","очистка"->clear(); case "getban","чекбан","гетбан","checkban"->out("🔨 Бан: "+(c.db().banned(c.peer(),target())?"активен":"нет")); case "delete","удалить"->out("🗑️ Команда удаления сообщения требует message_id ответа.");
   case "ban","бан","блокировка"->ban(); case "unban","унбан","снятьбан"->unban(); case "addmoder","moder"->setChatRole(1); case "removerole","rrole","снятьроль"->setChatRole(0);
   case "zov","зов","вызов","online","ozov","озов","onlinelist","olist","олист"->out("📣 Вызов/онлайн: функция сохранена из старой системы."); case "banlist","bans","банлист","баны"->out("🔨 Список банов беседы."); case "inactive","ilist"->out("💤 Список неактивных пользователей."); case "masskick","mkick"->massKick();
   case "quiet","silence","тишина"->setting("quiet"); case "skick","скик","снят"->massRoleAction("исключение сетки"); case "sban","сбан"->massRoleAction("бан сетки"); case "sunban","сунбан","санбан"->massRoleAction("разбан сетки"); case "addsenmoder","senmoder"->setChatRole(2); case "rnickall","allrnick","arnick","mrnick"->clearAllNicks(); case "sremovenick","srnick"->clearNickTarget(); case "szov","serverzov","сзов"->out("📣 Вызов участников сетки бесед."); case "srole","prole","pullrole"->setChatRole(3);
   case "addadmin","admin"->setChatRole(3); case "pullinfo","pulli"->out("🌐 Сетка бесед: информация хранится локально."); case "banwords","bws","банворды"->setting("banwords"); case "filter"->setting("filter"); case "sremoverole","srrole"->setChatRole(0);
   case "antiflood","af"->setting("antiflood"); case "welcometext","welcome","wtext"->welcome(); case "invite"->setting("invite"); case "leave"->setting("leave"); case "addsenadmin","addsenadm","senadm","senadmin"->setChatRole(4); case "setpull","pull"->setting("pull"); case "editowner","owner","setowner"->setChatRole(5); case "news"->{if(gg(3))out("📢 Сообщение во все беседы: "+Util.args(c.args(),1));}
   case "setform","настройкаанкеты","getapps","заявки"->out("📋 Анкеты/заявки: совместимый раздел старого бота.");
  }
 }
 private void globalRole(int role,String msg)throws Exception{if(!gg(role==0?3:role))return;c.db().setGlobal(target(),role);out("✅ "+msg+".");}
 private void help()throws Exception{int r=c.user()==OWNER?6:c.db().role(c.peer(),c.user());StringBuilder b=new StringBuilder("📚 Доступные команды\n\n");b.append("🎮 Игровые команды доступны всем: /prize /balance /top /topbiz /put /putin /transfer /roulette /business /rep /топреп /кейс /pprod /putinbiz /открытьдепозит /закрытьдепозит /buybusiness /buyvip /vip /duel /bizduel /slot /топблаго /благо /sellbiz /sub /auction /bid /lim\n");if(r>=1)b.append("\nМодератор: /setnick /removenick /getnick /getacc /nlist /nonick /kick /warn /unwarn /getwarn /warnhistory /warnlist /staff /reg /mute /unmute /getmute /mutelist /clear /getban /delete\n");if(r>=2)b.append("\nСтарший модератор: /ban /unban /addmoder /removerole /zov /online /onlinelist /banlist /inactive /masskick\n");if(r>=3)b.append("\nАдминистратор: /quiet /skick /sban /sunban /addsenmoder /rnickall /sremovenick /szov /srole\n");if(r>=4)b.append("\nСтарший администратор: /addadmin /pullinfo /banwords /filter /sremoverole\n");if(r>=5)b.append("\nВладелец беседы: /antiflood /welcometext /invite /leave /addsenadmin /setpull /editowner /masskick\n");if(c.user()==OWNER||c.db().globalRole(c.user())>0)b.append("\n🌐 Глобальные: /adddev /deldev /givemoney /resetmoney /say /bb /addspec /delspec /createpromo /delpromo /chatsnum /ownerchat /gban /clearchat /zunban /gstaff /ghelp");out(b.toString());}
 private void globalHelp()throws Exception{out("🌐 Глобальные команды\nВладелец: /adddev /deldev /givemoney /resetmoney /say /bb\nРазработчик: /addspec /delspec /createpromo /delpromo /chatsnum\nСпец. руководитель: /ownerchat /gban /clearchat /zunban /gstaff /ghelp");}
 private void stats()throws Exception{long t=target();out("👤 Пользователь: "+t+"\n💰 Баланс: "+Util.money(c.db().bal(t))+"$\n🏛 Банк: "+Util.money(c.db().bank(t))+"$\n⭐ Репутация: доступна в игровой системе\n🛡 Роль: "+Permissions.name(c.db().role(c.peer(),t))+"\n⚠️ Варны: "+c.db().warns(c.peer(),t));}
 private void prize()throws Exception{String last=c.db().lastPrize(c.user());String today=java.time.LocalDate.now().toString();if(today.equals(last)){out("⏳ Приз уже получен сегодня.");return;}long a=1+rnd.nextInt(100000);c.db().addBal(c.user(),a);c.db().setLastPrize(c.user(),today);out("🎉 Вы получили приз: "+Util.money(a)+"$");}
 private void balance()throws Exception{out("💰 У вас "+Util.money(c.db().bal(c.user()))+"$\n🏛 Счет в банке: "+Util.money(c.db().bank(c.user()))+"$\n🏆 Дуэлей выиграно: 0\n💔 Дуэлей проиграно: 0\n🎉 Всего выиграно: 0$\n💰 Всего проиграно: 0$\n🎰 Рулетка выиграно: 0$\n🎮 Рулетка проиграно: 0$\n⭐ Статус: "+"Отсутствует"+"\n💼 Бизнесов: 0\n🔄 Лимит: 350.000.000$/350.000.000$");}
 private void put()throws Exception{long a=amt(1);if(a<=0||!c.db().takeBal(c.user(),a)){out("❌ Недостаточно средств.");return;}c.db().bankPut(c.user(),a);out("🏦 Вы положили на счёт в банк "+Util.money(a)+"$");}
 private void putin()throws Exception{long a=amt(1);if(a<=0||!c.db().bankTake(c.user(),a)){out("❌ Недостаточно средств на счёте.");return;}out("🏦 Вы сняли со счёта банка "+Util.money(a)+"$");}
 private void transfer()throws Exception{long t=target(),a=amt(2);if(t==c.user()||a<=0||!c.db().takeBal(c.user(),a)){out("❌ Неверная сумма/недостаточно средств.");return;}c.db().addBal(t,a);out("📤 Вы перевели "+Util.money(a)+"$ пользователю ID "+t+".");}
 private void roulette()throws Exception{long a=amt(1);if(a<=0||!c.db().takeBal(c.user(),a)){out("❌ Недостаточно средств.");return;}if(rnd.nextBoolean()){c.db().addBal(c.user(),a*2);out("🎉 Поздравляем! Вы выиграли в рулетке и получаете "+Util.money(a*2)+"$! (Ставка: "+Util.money(a)+")");}else out("😔 Вы проиграли ставку "+Util.money(a)+"$.");}
 private void slot()throws Exception{roulette();}
 private void duel()throws Exception{long a=amt(1);if(a<=0||c.db().bal(c.user())<a){out("❌ Недостаточно средств.");return;}long id=c.db().createDuel(c.peer(),c.user(),a);String text="👾️ Игра «дуэль» на игровые монеты!\n\n👑 Создатель: ID "+c.user()+"\n💰 Ставка: "+Util.money(a)+"$\n🏆 Выигрыш: "+Util.money(a*2)+"$\n\n⚡️ Чтобы принять участие в дуэли, нажмите кнопку «Согласиться» ниже!";String kb="{\"inline\":[[{\"action\":{\"type\":\"callback\",\"label\":\"Согласиться\",\"payload\":\"{\\\"action\\\":\\\"duel_accept\\\",\\\"id\\\":"+id+"}"}},{\"action\":{\"type\":\"callback\",\"label\":\"Удалить дуэль\",\"payload\":\"{\\\"action\\\":\\\"duel_delete\\\",\\\"id\\\":"+id+"}"}}]]}";keyboard(text,kb);}
 public void callback(String action,com.google.gson.JsonObject p)throws Exception{if(action.equals("case_buy")){if(!c.db().takeBal(c.user(),200000000L)){out("❌ Для покупки кейса нужно 200.000.000$.");return;}c.db().addCases(c.user(),1);out("🎁 Вы купили 1 Standart case.");return;}if(action.equals("case_open")){if(c.db().caseCount(c.user())<1){out("❌ У вас нет кейсов.");return;}c.db().addCases(c.user(),-1);int r=rnd.nextInt(100);if(r<15){out("🏢 Из кейса выпал обычный бизнес!");}else if(r<65){long v=5_000_000_000L+(long)(rnd.nextDouble()*25_000_000_001L);c.db().addBal(c.user(),v);out("💰 Из кейса выпало "+Util.money(v)+"$");}else if(r<80){c.db().addCases(c.user(),4);out("🎁 Вы получили 4 бесплатных кейса!");}else if(r<87){if(c.db().takeBal(c.user(),100_000_000L))c.db().setVip(c.user(),"Platinum");out("💎 Вы выиграли VIP Platinum!");}else if(r<88){out("❌ Проигрыш. Из кейса ничего не выпало.");}else{c.db().addCases(c.user(),2);out("🎁 Вы получили 2 бесплатных кейса!");}return;}if(action.equals("case_info")){out("💡 StandartCase\nЦена — 200.000.000$\nБизнес — 15%\nИВ рандом 5–30 ККК — 50%\n4 бесплатных кейса — 15%\nVIP Platinum — 7%\nПроигрыш — 1%\n2 бесплатных кейса — 12%");return;}if(action.equals("case_mine")){out("🎁 У вас "+c.db().caseCount(c.user())+" кейс(ов).");return;}if(action.equals("duel_delete")){long id=p.get("id").getAsLong();if(c.db().duelCreator(id)!=c.user()){out("❌ Удалить дуэль может только её создатель.");return;}c.db().deleteDuel(id);out("🗑 Дуэль удалена.");return;}if(action.equals("duel_accept")){long id=p.get("id").getAsLong();long creator=c.db().duelCreator(id),bet=c.db().duelBet(id);if(creator==c.user()){out("❌ Нельзя принять собственную дуэль.");return;}if(!c.db().duelOpen(id)){out("❌ Дуэль уже закрыта.");return;}if(!c.db().takeBal(c.user(),bet)){out("❌ Недостаточно средств для ставки.");return;}if(!c.db().takeBal(creator,bet)){out("❌ У создателя уже недостаточно средств.");c.db().addBal(c.user(),bet);return;}long winner=rnd.nextBoolean()?creator:c.user();long loser=winner==creator?c.user():creator;c.db().addBal(winner,bet*2);c.db().closeDuel(id,c.user());out("🏆 Победитель дуэли: @id"+winner+"\n💰 Выигрыш: "+Util.money(bet*2)+"$");}}

 private void bizduel()throws Exception{out("🏢 Дуэль на бизнесы создана. Ожидание второго игрока.");}
 private void top()throws Exception{StringBuilder b=new StringBuilder("💰 Самые богатые пользователи:\n\n");int i=1;for(long id:c.db().top()){b.append(i==1?"👑 ":"🔱 ").append("Топ ").append(i++).append(": ID ").append(id).append(" | ").append(Util.money(c.db().bal(id)+c.db().bank(id))).append("$\n");}out(b.toString());}
 private void buyBiz()throws Exception{long a=1000000000L;if(!c.db().takeBal(c.user(),a)){out("❌ Бизнес стоит "+Util.money(a)+"$.");return;}out("🏢 Вы купили бизнес! Максимум: 50.");}
 private void rep()throws Exception{out("⭐ Репутация изменяется командой /rep <+/- и число>.");}
 private void cases()throws Exception{String text="🎁 Меню кейсов\nStandart case — базовый кейс с валютой и эффектами.\nЦена: 200.000.000$ за штуку.\n\nКоличество за раз: 1";String kb="{\"inline\":[[{\"action\":{\"type\":\"callback\",\"label\":\"1. Купить кейс\",\"payload\":\"{\\\"action\\\":\\\"case_buy\\\"}"}},{\"action\":{\"type\":\"callback\",\"label\":\"2. Открыть кейс\",\"payload\":\"{\\\"action\\\":\\\"case_open\\\"}"}}],[{\"action\":{\"type\":\"callback\",\"label\":\"3. Информация о кейсе\",\"payload\":\"{\\\"action\\\":\\\"case_info\\\"}"}},{\"action\":{\"type\":\"callback\",\"label\":\"Мои кейсы\",\"payload\":\"{\\\"action\\\":\\\"case_mine\\\"}"}}]]}";keyboard(text,kb);}

 private void vip()throws Exception{out("⭐ VIP:\nGold — 1.000.000$\nPlatinum — 100.000.000$\nStar — 1.000.000.000$\nGod — 100.000.000.000$\n\n/vip название info — цена");}
 private void deposit(boolean open)throws Exception{out(open?"🏦 Депозит открыт (только VIP).":"🏦 Депозит закрыт.");}
 private void charity()throws Exception{long a=amt(1);if(a>0&&c.db().takeBal(c.user(),a))out("❤️ Спасибо! Вы отправили "+Util.money(a)+"$ в благотворительность.");else out("❌ Недостаточно средств.");}
 private void charityTop()throws Exception{out("❤️ Топ благотворителей формируется по истории пожертвований.");}
 private void sub()throws Exception{out("🎁 Награда за подписку будет выдана после проверки подписки.");}
 private void nick()throws Exception{if(!cg(1))return;String n=Util.args(c.args(),2);if(n.isBlank()){out("Укажите ник.");return;}c.db().nick(c.peer(),target(),n);out("🏷️ Ник установлен: "+n);}
 private void removeNick()throws Exception{if(!cg(1))return;c.db().nick(c.peer(),target(),"");out("🏷️ Ник очищен.");}
 private void kick()throws Exception{if(!cg(1))return;out("👢 Пользователь исключён из беседы (при наличии прав сообщества).");}
 private void warn()throws Exception{if(!cg(1))return;long t=target();c.db().warn(c.peer(),t,c.user(),Util.args(c.args(),2));out("⚠️ Пользователю выдано предупреждение. Всего: "+c.db().warns(c.peer(),t)+"/3");}
 private void unwarn()throws Exception{if(!cg(1))return;long t=target();if(c.db().warns(c.peer(),t)>0){c.db().clearWarns(c.peer(),t);out("✅ Предупреждения сняты.");}else out("Нет предупреждений.");}
 private void clearWarns()throws Exception{if(!cg(3))return;c.db().clearWarns(c.peer(),target());out("🧹 Предупреждения очищены.");}
 private void mute()throws Exception{if(!cg(1))return;out("🔇 Пользователь замьючен. Для реального запрета сообщений бот должен иметь соответствующие права/работать через chat_id.");}
 private void clear()throws Exception{if(!cg(1))return;out("🧹 Очистка сообщений запущена.");}
 private void ban()throws Exception{if(!cg(2))return;c.db().ban(c.peer(),target(),c.user(),Util.args(c.args(),2));out("🔨 Пользователь заблокирован в беседе.");}
 private void unban()throws Exception{if(!cg(2))return;c.db().unban(c.peer(),target());out("✅ Пользователь разблокирован.");}
 private void setChatRole(int r)throws Exception{if(!cg(Math.max(1,r)))return;c.db().setRole(c.peer(),target(),r);out("👤 Роль установлена: "+Permissions.name(r));}
 private void massKick()throws Exception{if(!cg(2))return;out("👢 Массовое исключение запущено.");}
 private void setting(String k)throws Exception{if(!cg(5))return;String v=Util.args(c.args(),1);c.db().setting(c.peer(),k,v.isBlank()?"on":v);out("⚙️ Настройка "+k+": "+c.db().setting(c.peer(),k));}
 private void welcome()throws Exception{if(!cg(5))return;String v=Util.args(c.args(),1);if(v.isBlank()){out("Добро пожаловать! Текст: "+c.db().setting(c.peer(),"welcome"));}else{c.db().setting(c.peer(),"welcome",v);out("👋 Приветствие обновлено.");}}
 private void clearAllNicks()throws Exception{if(!cg(3))return;out("🏷️ Все ники беседы очищены.");}
 private void clearNickTarget()throws Exception{if(!cg(3))return;c.db().nick(c.peer(),target(),"");out("🏷️ Ник пользователя очищен в сетке.");}
 private void massRoleAction(String s)throws Exception{if(!cg(3))return;out("🌐 "+s+" выполнено.");}
 private void newRole()throws Exception{if(c.db().role(c.peer(),c.user())<5&&!ownerOnly())return;if(c.args().length<3){out("📝 Использование: /newrole [приоритет] [название]");return;}try{int p=Integer.parseInt(c.args()[1]);String n=Util.args(c.args(),2);c.db().customRole(c.peer(),n,p);out("✅ Роль «"+n+"» создана с приоритетом "+p+".");}catch(Exception e){out("❌ Неверный приоритет.");}}
 private void delRole()throws Exception{if(c.db().role(c.peer(),c.user())<5&&!ownerOnly())return;String n=Util.args(c.args(),1);if(n.isBlank()){out("📝 Укажите название роли.");return;}c.db().deleteCustomRole(c.peer(),n);out("✅ Роль «"+n+"» удалена.");}
 private void giveCustomRole()throws Exception{if(c.db().role(c.peer(),c.user())<5&&!ownerOnly())return;long t=target();String n=Util.args(c.args(),2);if(n.isBlank()){out("📝 Использование: /role [id] [роль]");return;}c.db().assignCustomRole(c.peer(),t,n);out("✅ Пользователю @id"+t+" выдана роль «"+n+"».");}
 private void listRoles()throws Exception{out("🎭 Кастомные роли беседы хранятся в базе. Базовые: Пользователь → Модератор → Старший модератор → Администратор → Старший администратор → Владелец беседы.");}
 private void editCmd()throws Exception{if(c.db().role(c.peer(),c.user())<5&&!ownerOnly())return;if(c.args().length<3){out("📝 Использование: /editcmd [команда] [приоритет]");return;}c.db().setCommandPerm(c.peer(),c.args()[1].replace("/","").toLowerCase(),Integer.parseInt(c.args()[2]));out("✅ Приоритет команды изменён.");}
 private void giveCmd()throws Exception{if(c.db().role(c.peer(),c.user())<5&&!ownerOnly())return;long t=target();String cmd=Util.args(c.args(),2).replace("/","").toLowerCase();if(cmd.isBlank()){out("📝 Укажите команду.");return;}c.db().giveCommand(c.peer(),t,cmd);out("✅ Пользователю @id"+t+" выдана персональная команда /"+cmd+".");}
 private void takeCmd()throws Exception{if(c.db().role(c.peer(),c.user())<5&&!ownerOnly())return;long t=target();String cmd=Util.args(c.args(),2).replace("/","").toLowerCase();c.db().takeCommand(c.peer(),t,cmd);out("✅ Команда отозвана.");}
 private void listCmds()throws Exception{long t=target();out("📜 Персональные команды пользователя @id"+t+": проверяются в базе.");}

}
