package ru.faktish.vk;
import com.google.gson.*;import java.net.*;import java.net.http.*;import java.nio.charset.*;import java.util.*;
public class VkClient{
 private final String token,ver;private final long group;private final HttpClient http=HttpClient.newHttpClient();private String server,key,ts="0";
 public VkClient(String t,String v,long g){token=t;ver=v;group=g;}
 public JsonObject api(String method,Map<String,String> p)throws Exception{Map<String,String> m=new LinkedHashMap<>(p);m.put("access_token",token);m.put("v",ver);StringBuilder b=new StringBuilder();for(var e:m.entrySet()){if(b.length()>0)b.append('&');b.append(URLEncoder.encode(e.getKey(),StandardCharsets.UTF_8)).append('=').append(URLEncoder.encode(e.getValue(),StandardCharsets.UTF_8));}HttpRequest r=HttpRequest.newBuilder(URI.create("https://api.vk.com/method/"+method)).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(b.toString())).build();String s=http.send(r,HttpResponse.BodyHandlers.ofString()).body();JsonObject o=JsonParser.parseString(s).getAsJsonObject();if(o.has("error"))throw new RuntimeException(o.getAsJsonObject("error").get("error_msg").getAsString());return o.getAsJsonObject("response");}
 public void init()throws Exception{JsonObject o=api("groups.getLongPollServer",Map.of("group_id",String.valueOf(group)));server=o.get("server").getAsString();key=o.get("key").getAsString();ts=o.get("ts").getAsString();}
 public JsonObject poll()throws Exception{String u=server+"?act=a_check&key="+URLEncoder.encode(key,StandardCharsets.UTF_8)+"&wait=25&ts="+ts+"&version=3";HttpRequest r=HttpRequest.newBuilder(URI.create(u)).GET().build();String s=http.send(r,HttpResponse.BodyHandlers.ofString()).body();JsonObject o=JsonParser.parseString(s).getAsJsonObject();if(o.has("ts"))ts=o.get("ts").getAsString();if(o.has("failed")){init();return null;}return o;}
 public long send(long peer,String text)throws Exception{return api("messages.send",Map.of("peer_id",String.valueOf(peer),"message",text,"random_id",String.valueOf(System.nanoTime()))).get("response").getAsLong();}
 public long sendKeyboard(long peer,String text,String keyboard)throws Exception{Map<String,String> m=new LinkedHashMap<>();m.put("peer_id",String.valueOf(peer));m.put("message",text);m.put("random_id",String.valueOf(System.nanoTime()));m.put("keyboard",keyboard);return api("messages.send",m).get("response").getAsLong();}
 public void deleteConversation(long peer)throws Exception{api("messages.deleteConversation",Map.of("peer_id",String.valueOf(peer)));}
 public void kick(long chatPeer,long user)throws Exception{api("messages.removeChatUser",Map.of("chat_id",String.valueOf(chatPeer-2000000000L),"user_id",String.valueOf(user)));}
 public void ban(long groupId,long user)throws Exception{api("groups.ban",Map.of("group_id",String.valueOf(groupId),"owner_id",String.valueOf(user)));}
}
